In [7]:
import numpy as np

# marks=[10,20,30,40,50]

#define a numpy array
marks=np.array([10,20,30,40,50])

print(marks)

[10.1  20.2  30.9  40.   50.76]


In [8]:
#dimension of the array
print(marks.ndim)

#shape of the array
print(marks.shape)

#size of the array
print(marks.size)

#data type of the array
print(marks.dtype)

1
(5,)
5
float64


In [11]:
data_2d=np.array([[50,20,10],[20,40,30],[10,20,10]])

#dimension of the array
print(data_2d.ndim)

#shape of the array
print(data_2d.shape)

#size of the array
print(data_2d.size)

#data type of the array
print(data_2d.dtype)

2
(3, 3)
9
int64


In [16]:
intialised_array=np.zeros((5,5))
print(intialised_array)

NameError: name 'int64' is not defined

In [21]:
intialised_array=np.ones((5,5)).astype('int16')
print(intialised_array)

print(intialised_array.dtype)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
int16


In [25]:
#accessing np arrays
marks=np.array([10,20,30,40,50])
print(marks[4])

data_2d=np.array([[50,20,10],[20,40,30],[10,20,10]])
print(data_2d[1,1])


50
40


In [40]:
data_2d=np.array([[50,20,10],[20,40,30],[10,20,10]])
print(data_2d)

#to slice the np array and acces only 40,30,20,20 as 2*2 array
sliced_array=data_2d[1:,1:]
print(sliced_array)

sliced_2=data_2d[:2,:2]
print(sliced_2)

slice_3=data_2d[:2,]
print(slice_3)

[[50 20 10]
 [20 40 30]
 [10 20 10]]
[[40 30]
 [20 10]]
[[50 20]
 [20 40]]
[[50 20 10]
 [20 40 30]]


In [54]:
marks=np.array([10,20,30,40,50])

reversed=marks[::-1]
print(reversed)


#reverse sliced_3
reversed_2=slice_3[::,::-1]
print(reversed_2)

[50 40 30 20 10]
[[10 20 50]
 [30 40 20]]


In [64]:
ids=np.arange(10)
print(ids)

ids=np.arange(10,20)
print(ids)

#even numbers bet 0 and 10
ids=np.arange(2,11,2)
print(ids)


[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[ 2  4  6  8 10]


In [117]:
loto=np.linspace(0,40,9)
print(loto)

print(np.linspace(0,100,11))

[ 0.  5. 10. 15. 20. 25. 30. 35. 40.]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [115]:
random=np.random.rand(5)
print(random)

print(np.random.randint(1,40,6))

[0.91036071 0.31085649 0.78875432 0.09963918 0.39537788]
[12 26 15 34  6 37]


In [124]:
marks=np.array([[50,20,10],[20,40,30],[10,20,10]])
print(marks*2)
print(marks-10)


[[100  40  20]
 [ 40  80  60]
 [ 20  40  20]]
[[40 10  0]
 [10 30 20]
 [ 0 10  0]]


In [133]:
x=np.zeros((2,3))
print(x)

flipped=np.reshape(x,(3,2))
print(flipped)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [145]:
marks=np.array([[50,20,10],[20,40,30],[10,20,10]])
print(marks)
print(marks[0])
print(marks[:2])

print(marks[:,1])

[[50 20 10]
 [20 40 30]
 [10 20 10]]
[50 20 10]
[[50 20 10]
 [20 40 30]]
[20 40 20]


In [146]:
marks=np.array([[50,20,10],[20,40,30],[10,20,10]])

print(marks.mean())

23.333333333333332


In [159]:
marks=np.array([[50,20,10],[20,40,30],[10,20,10]])
print(marks)


print(np.argsort(marks)) #order matrix

# print(marks[marks[:,1].argsort()])

[[50 20 10]
 [20 40 30]
 [10 20 10]]
[[2 1 0]
 [0 2 1]
 [0 2 1]]
[[50 20 10]
 [10 20 10]
 [20 40 30]]


In [163]:
marks=np.array([[50,20,10],[20,40,30],[10,20,10]])
print(marks)
#swap row 0 and 1
marks[[0,1]]=marks[[1,0]]
print(marks)

[[50 20 10]
 [20 40 30]
 [10 20 10]]
[[20 40 30]
 [50 20 10]
 [10 20 10]]


In [174]:
data=np.array([[1,4,9],[16,25,36],[49,64,81]])
print(data.mean())

sqrt=np.sqrt(data)
print(sqrt.mean())


print(np.std(data))
print(data.max()) 
print(data.min())


print(sqrt**2)

31.666666666666668
5.0
26.474306202219704
81
1
[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]]


In [176]:
help(np.min)

Help on _ArrayFunctionDispatcher in module numpy:

min(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Return the minimum of an array or minimum along an axis.
    
    Parameters
    ----------
    a : array_like
        Input data.
    axis : None or int or tuple of ints, optional
        Axis or axes along which to operate.  By default, flattened input is
        used.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, the minimum is selected over multiple axes,
        instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternative output array in which to place the result.  Must
        be of the same shape and buffer length as the expected output.
        See :ref:`ufuncs-output-type` for more details.
    
    keepdims : bool, optional
        If this is set to True, the axes which are reduced are left
        in the result as dimensions with size one. With this option,
        

In [177]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [178]:
my_array=[0,1,0,2,3,4,5]
print(np.nonzero(my_array))

(array([1, 3, 4, 5, 6]),)


In [180]:
# help(np.bincount)
my_array=[0,1,0,2,3,4,5]
print(np.bincount(my_array))

[2 1 1 1 1 1]
